const express = require('express');
const userRoutes = require('./user.routes');
const adminRoutes = require('./admin.routes');
const courseRoutes = require('./course.routes');
const lessonRoutes = require('./lesson.routes');
const progressRoutes = require('./progress.routes');
const noteRoutes = require('./note.routes');
const enrollmentRoutes = require('./enrollment.routes');
const moduleRoutes = require('./module.routes');
const authRoutes = require('./auth.routes');
const reviewRoutes = require('./review.routes');
const submissionRoutes = require('./submission.routes');
const wishlistRoutes = require('./wishlist.routes');
const muxRoutes = require('./mux.routes');
const notificationRoutes = require('./notification.routes');
const paymentRoutes = require('./payment.routes');
const certificateRoutes = require('./certificate.routes');
const certificateTemplateRoutes = require('./certificateTemplate.routes');
const institutionTemplateRoutes = require('./institutionTemplate.routes');
const liveSessionRoutes = require('./liveSession.routes');
const liveRecordingRoutes = require('./liveRecording.routes');
const attendanceRoutes = require('./attendance.routes');
const quizAttemptRoutes = require('./quizAttempt.routes');
const discussionRoutes = require('./discussion.routes');
const institutionRoutes = require('./institution.routes');
const institutionAttendanceRoutes = require('./institutionAttendance.routes');
const institutionFeeRoutes = require('./institutionFee.routes');
const ticketRoutes = require('./ticket.routes');

const router = express.Router();

router.use('/users', userRoutes);
router.use('/admin', adminRoutes);
router.use('/courses', courseRoutes);
router.use('/lessons', lessonRoutes);
router.use('/progress', progressRoutes);
router.use('/notes', noteRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/modules', moduleRoutes);
router.use('/reviews', reviewRoutes);
router.use('/submissions', submissionRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/mux', muxRoutes);
router.use('/notifications', notificationRoutes);
router.use('/payments', paymentRoutes);
router.use('/certificates', certificateRoutes);
router.use('/platform-admin/certificate-templates', certificateTemplateRoutes);
router.use('/institution-admin/certificate-templates', institutionTemplateRoutes);
router.use('/live-sessions', liveSessionRoutes);
router.use('/live-recordings', liveRecordingRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/quizzes', quizAttemptRoutes);
router.use('/discussions', discussionRoutes);
router.use('/institution', institutionRoutes);
router.use('/institution-attendance', institutionAttendanceRoutes);
router.use('/institution-fees', institutionFeeRoutes);
router.use('/tickets', ticketRoutes);

module.exports = router;

