const mongoose = require('mongoose');

const liveRecordingSchema = new mongoose.Schema({
  sessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'LiveSession', required: true, index: true },
  courseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true, index: true },
  tutorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  
  title: { type: String, required: true, trim: true },
  description: { type: String, trim: true },
  
  // Storage & Streaming (MUX or External)
  provider: { type: String, enum: ['mux', 'cloudinary', 'external'], default: 'mux' },
  muxAssetId: { type: String },
  muxPlaybackId: { type: String },
  streamUrl: { type: String }, // e.g. https://stream.mux.com/{playbackId}.m3u8
  processingStatus: { 
    type: String, 
    enum: ['uploading', 'processing', 'ready', 'failed'], 
    default: 'uploading' 
  },
  
  thumbnailUrl: { type: String }, // Can be generated by Mux or custom uploaded
  duration: { type: Number },
  uploadType: { type: String, enum: ['direct', 'external', 'google_drive', 'meet_recording'], default: 'direct' },
  
  // Visibility & State Management
  status: { type: String, enum: ['draft', 'published', 'discarded'], default: 'draft', index: true },
  visibility: { type: String, enum: ['enrolled_only'], default: 'enrolled_only' },
  publishedAt: { type: Date },
  deletedAt: { type: Date, default: null },
}, { timestamps: true });

module.exports = mongoose.model('LiveRecording', liveRecordingSchema);
